Sistema_de_Facturacion/Controllers/FacturasController.cs
using Sistema_de_Facturacion.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rotativa;

namespace Sistema_de_Facturacion.Controllers
{
    public class FacturasController : Controller
    {
       

        private FacturaRepos _repos;
        private DetalleReciboRepos _rep;

        public FacturasController()
        {
            _repos = new FacturaRepos();
            _rep = new DetalleReciboRepos();
        }
       
        // GET: Facturas
        public ActionResult Facturar()
        {
            try
            {
                if (Session["UsuarioId"] == null)
                {
                    Session["NoSesion"] = "debes iniciar sesión";
                    return RedirectToAction("Index", "Home", null);
                }
                int idUsuario = (int)Session["UsuarioId"];
                
                
                ViewBag.Razon = (string)Session["UsuarioRazon"];
                ViewBag.Rut = (long)Session["UsuarioRut"];
                ViewBag.Dire = (string)Session["UsuarioDire"];
                ViewBag.Tel = (long)Session["UsuarioTel"];

                Imagenes img = new Imagenes();
                var imagen = img.GetImagen(idUsuario);

                if(imagen == null)
                {
                    return View();
                }
                ViewBag.logo = imagen.Nombre;
                return View();
            }
            catch
            {
                return RedirectToAction("Index", "Home", null);
            }
        }
        public ActionResult AutoCLiente(string term)
        {
            var model= _repos.GetClient(term);
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Facturar(string nombre, string[] productos, int[] cantidad, DateTime fecha /*int? dia, int? mes, double? anio*/, string subtotal, string total, string moneda, string tipo_cambio, string nroFactura)
        {
            try
            {
                int idUsuario = (int)Session["UsuarioId"];


                if (tipo_cambio == "")
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
              
                double Subtotal = (double.Parse(subtotal));
                double Total = (double.Parse(total));
                double Tc = double.Parse(tipo_cambio)/10;
               
                Clientes Idcient = new Clientes();
                Idcient = _repos.GetIdClient(nombre);
                int Idc = Idcient.IdCliente;

                string product = null;

                for (var i = 0; i < productos.Count(); i++)
                {
                    if (productos[i] != "")
                    {
                        product = product + "<li>" + cantidad[i] + " unidades de " + productos[i] + "</li>";

                    }
                }
               
                FacturaRepos f = new FacturaRepos();
                if(f.ActualizaStock(productos, cantidad)==true)
                {
                    _repos.Agregar_detalle(idUsuario, Idc, product,fecha /*dia, mes, anio*/, (Subtotal / 100), (Total / 100), moneda, nroFactura, nombre,Tc);
                    _repos.ActualizaEstadoCuentaFactura(Idc, Total/100,moneda,Tc);
                }
                else
                {
                ViewBag.error = "No hay stock de algún producto, por lo cual no se emitió la factura";
                return View();
                }

                ViewBag.nombre = nombre;
                ViewBag.nroFactura = nroFactura;
                ViewBag.producto = product;
                ViewBag.fecha = fecha;
                ViewBag.moneda = moneda;
                ViewBag.subtotal = subtotal;
                ViewBag.total = total;

                return View("DetalleFactura");
            }
            catch
            {
                ViewBag.error = "No se emotió la factura";
                return View();
            }
        }
      
        public ActionResult DetalleFacturas(int? cantidad_facturas)
        {
            try
            {
                var model = new List<DetalleFactura>();
                
                if (Session["UsuarioId"] == null)
                {
                    Session["NoSesion"] = "debes iniciar sesión";
                    return RedirectToAction("Index", "Home", null);
                }
                int idUsuario = (int)Session["UsuarioId"];
                if (cantidad_facturas == null) {
                    model = _repos.ObtenerTodos(idUsuario);
                }
                

                return View(model);
            }
            catch
            {
                return RedirectToAction("Index", "Home", null);
            }  
        }
        [HttpPost]
        public ActionResult DetalleFacturas(string nombreCliente, DateTime fecha)
        {

            return View();
        }

        public ActionResult ReciboDePago()
        {
            try
            {
                if (Session["UsuarioId"] == null)
                {
                    Session["NoSesion"] = "debes iniciar sesión";
                    return RedirectToAction("Index", "Home", null);
                }
                return View();
            }
            catch
            {
                return RedirectToAction("Index", "Home", null);
            }
        }

        [HttpPost]
        public ActionResult ReciboDePago(string nro_recibo, string[] nro_factura, string moneda, string monto, string nombre_cliente, string tipo_pago, long? nro_cheque, string banco, string dia_mes,string anio,string Tipo_cambio)
        {
            try
            {
                int idUsuario = (int)Session["UsuarioId"];
                // (moneda){ 0  = U$S : 1 = $ }
                // (tipo de pago){ 0  = cheque : 1 = efectivo }
                double _monto = double.Parse(monto);
                string fecha = dia_mes + " " + anio;
                double Tc = double.Parse(Tipo_cambio) / 10;
                Clientes Idcient = new Clientes();
                Idcient = _repos.GetIdClient(nombre_cliente);
                int Idc = Idcient.IdCliente;

                string NroFact = null;
                DetalleRecibo r = new DetalleRecibo();
                r.NroRecibo = nro_recibo;
                if (moneda == "0") { r.Moneda = "U$S"; }
                if (moneda == "1") { r.Moneda = "$"; }
                r.Monto = _monto;
                r.Cliente = nombre_cliente;
                if (tipo_pago == "0")
                {
                    r.TipoPago = "Cheque";
                }
                if (tipo_pago == "1")
                {
                    r.TipoPago = "Efectivo";
                }
                r.NroCheque = nro_cheque;
                r.Banco = banco;
                for (var i = 0; i < nro_factura.Count(); i++)
                {
                    if (nro_factura[i] != "")
                    {
                        NroFact = NroFact + "<li>" + nro_factura[i] + "</li>";

                    }
                }
                r.NroFactura = NroFact;
                r.Fecha = fecha;
                r.TipoCambio = Tc;
                _rep.AgregarDetalleRecibo(r,idUsuario);
                _repos.ActualizaEstadoCuentaRecibo(Idc, moneda, _monto, Tc);

                return RedirectToAction("DetalleRecibos");
            }
            catch
            {
                return RedirectToAction("Index", "Home", null);
            }
        }

        public ActionResult DetalleRecibos()
        {
            try
            {
                if (Session["UsuarioId"] == null)
                {
                    Session["NoSesion"] = "debes iniciar sesión";
                    return RedirectToAction("Index", "Home", null);
                }
                int idUsuario = (int)Session["UsuarioId"];
                var model = _rep.ObtenerTodos(idUsuario);
                return View(model);
            }
            catch
            {
                return RedirectToAction("Index", "Home", null);
            }
        }
        public ActionResult PDF_Factura()
        {
            int idUsuario = (int)Session["UsuarioId"];

            return new ViewAsPdf("Facturar")
            {
                //FileName = Server.MapPath("~/Context/Factura.pdf")
                PageOrientation = Rotativa.Options.Orientation.Landscape,
                PageSize = Rotativa.Options.Size.A4
            };
        }
        public ActionResult SelectForName(string term)
        {
            int idUsuario = (int)Session["UsuarioId"];
            var name = _repos.GetFacturaForName(idUsuario, term);
            return Json(name, JsonRequestBehavior.AllowGet);
        }
        public ActionResult SearchFactura(string term)
        {
            int idUsuario = (int)Session["UsuarioId"];
            var model = _repos.GetDetalleFactura(idUsuario,term);
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        public ActionResult SelectForDate(string term, string term2)
        {
            
            string dateInit = term;
            DateTime parsedDateInit = DateTime.Parse(dateInit);
            string dateFinal = term2;
            DateTime parsedDateFinal = DateTime.Parse(dateFinal);
            if (parsedDateInit > parsedDateFinal)
            {
                return null;
            }
            int idUsuario = (int)Session["UsuarioId"];
            var model = _repos.GetDetalleFactura2(idUsuario, parsedDateInit, parsedDateFinal);
            if (model.Count() != 0)
            {
                ViewBag.fecha = model[0].Fecha_emision.Date;
            }
            
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        public ActionResult NroFactura()
        {
            int idUsuario = (int)Session["UsuarioId"];

Sistema_de_Facturacion/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.ModelBinding;
using System.Web.Mvc;
using Sistema_de_Facturacion.Models;
using System.IO;

namespace Sistema_de_Facturacion.Controllers
{
    public class UsuariosController : Controller
    {
        private UsuarioRepos _repos;
        public UsuariosController()
        {
            _repos = new UsuarioRepos();
        }

        public ActionResult Registro()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Registro(Usuarios usr)
        {
            var imagen = new Imagenes();
            if (ModelState.IsValid)
            {
                _repos.Registrarse(usr);
                var usuario = _repos.GetUsuario(usr.Nombre, usr.Contraseña);
                imagen.IdUsuario = usuario.Id;
                imagen.Nombre = "http://www.aesoftmarket.com/uploads/fe-logo-8076354209.png";
                imagen.Extension = "imagen/png";
                imagen.GuardarImagen(imagen);
                
                ModelState.Clear();
                
            }

            return View("Logearse");
        }

        // GET: Usuarios
        public ActionResult Logearse()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Logearse(Usuarios usr)
        {         
            var usuario = _repos.logeo(usr);

            if (usuario != null)
            {
                Session["UsuarioId"] = usuario.Id;
                Session["UsuarioRazon"] = usuario.RazonSocial;
                Session["UsuarioRut"] = usuario.Rut;
                Session["UsuarioDire"] = usuario.Direccion;
                Session["UsuarioTel"] = usuario.Telefono;



                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.error = "Error de credenciales, intentelo nuevamente";
            }
       
            return View();


        }


        // GET: Usuarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios usuarios = _repos.GetUsuario(id);
            Imagenes img = new Imagenes();
            var imagen = img.GetImagen(id);
            if(imagen == null)
            {
                return View(usuarios);
            }
            ViewBag.img = imagen.Nombre;
            

            if (usuarios == null)
            {
                return HttpNotFound();
            }
            return View(usuarios);
        }



        // GET: Usuarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios usuarios = new Usuarios();
            usuarios = _repos.GetUsuario(id);
            if (usuarios == null)
            {
                return HttpNotFound();
            }
            return View(usuarios);
        }

        // POST: Usuarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Nombre,RazonSocial,Rut,Direccion,Telefono,Contraseña")] Usuarios usuarios)
        {
            if (usuarios.Nombre!=null && usuarios.RazonSocial!=null && usuarios.Rut!=0 && usuarios.Direccion!= null && usuarios.Telefono!=0 && usuarios.Contraseña!= null)
            {
                int idUsuario = (int)Session["UsuarioId"];
                usuarios.Id = idUsuario;
                usuarios.ConfirmarContraseña = usuarios.Contraseña;
                _repos.Editar(usuarios);
                ViewBag.msj = "Usuario actualizado correctamente";
                return View(usuarios);
            }
            return View(usuarios);
        }
        [HttpPost]
        public ActionResult SubirImagen(HttpPostedFileBase file)
        {
            int idUsuario = (int)Session["UsuarioId"];
            if(file!=null && file.ContentLength > 0)
            {
                Imagenes imagen = new Imagenes();
                var img = imagen.GetImagen(idUsuario);
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Context"), fileName);
                
                file.SaveAs(path);
                img.Nombre = fileName;
                img.Extension = file.ContentType;
                img.IdUsuario = idUsuario;
                img.ActualizarImagen(img);
            }
            return Redirect("Details/" + idUsuario);
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //       _repos.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}
    

Sistema_de_Facturacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sistema de facturación</title>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css?family=Merienda+One" rel="stylesheet">


    <style>
        body {
            background: white; /*url("https://previews.123rf.com/images/siraphol/siraphol1504/siraphol150405358/39057920-blanca-ladrillo-de-hormig%C3%B3n-texturas-de-la-pared-de-fondo.jpg");*/
            background-repeat: no-repeat;
            background-size: 100% 100%;
            background-attachment: fixed;
        }

        td {
            font-weight: 600;
        }

        .nav {
            margin-top: 6px;
        }

        ul, ol {
            list-style: none;
        }

        .nav > li {
            float: left;
            margin: 0 5px 0 5px;
        }

        .nav li a {
            background-color: #000;
            color: #fff;
            text-decoration: none;
            padding: 10px 12px;
            display: block;
            border-radius: 5px;
        }

            .nav li a:hover {
                background-color: #434343;
            }

        .nav li ul {
            display: none;
            position: absolute;
            min-width: 140px;
            margin-left: -41px;
        }

        .nav li:hover > ul {
            display: block;
        }

        .nav li ul li {
            position: relative;
        }

        #stock {
            width: 98px;
            text-align: center;
        }

        #clientes {
            width: 98px;
            text-align: center;
        }

        #mi_perfil {
            width: 98px;
            text-align: center;
        }
    </style>
    

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav">
                    @if (Session["UsuarioId"] == null)
                    {
                        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                        <li style="float:right">@Html.ActionLink("Registrarse", "Registro", "Usuarios")</li>
                        <li style="float:right">@Html.ActionLink("Iniciar sesión", "Logearse", "Usuarios")</li>
                    }
                    else
                    {
                        <li>
                            @Html.ActionLink("Facturación", "Facturar", "Facturas")
                            <ul>
                                <li>@Html.ActionLink("Facturar", "Facturar", "Facturas")</li>
                                <li>@Html.ActionLink("Listado Facturas", "DetalleFacturas", "Facturas")</li>
                                <li>@Html.ActionLink("Pagos", "DetalleRecibos", "Facturas")</li>
                                <li>@Html.ActionLink("Recibo de Pago", "ReciboDePago", "Facturas")</li>
                                <li>@Html.ActionLink("Listado Recibos", "DetalleRecibos", "Facturas")</li>
                            </ul>
                        </li>
                        <li id="stock">
                            @Html.ActionLink("Stock", "Index", "Productos")
                            <ul>
                                <li>@Html.ActionLink("Ver Stock", "Index", "Productos")</li>
                                <li>@Html.ActionLink("Agregar", "Create", "Productos")</li>
                            </ul>
                        </li>
                        <li id="clientes">
                            @Html.ActionLink("Clientes", "Index", "Clientes")
                            <ul>
                                <li>@Html.ActionLink("Ver Clientes", "Index", "Clientes")</li>
                                <li>@Html.ActionLink("Agregar", "Create", "Clientes")</li>
                            </ul>
                        </li>
                        <li id="mi_perfil">
                            @Html.ActionLink("Mi Perfil", "Details", "Usuarios", new { id = (int)Session["UsuarioId"] }, null)
                            <ul>
                                <li>@Html.ActionLink("Editar", "Edit", "Usuarios", new { id = (int)Session["UsuarioId"] }, null)</li>
                                <li>@Html.ActionLink("Cerrar sesión", "CerrarSesion", "Home")</li>
                            </ul>
                        </li>
                        <li> @Html.ActionLink("Cerrar sesión", "CerrarSesion", "Home") </li>

                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr style="border: solid 1px; color:black;" />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sistema de facturación</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</body>
</html>